parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - 'jest-formatting'
extends:
  - alloy
  - alloy/typescript
  - eslint:recommended
  - plugin:jest/recommended
  - plugin:unicorn/recommended
  - plugin:jest-formatting/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
ignorePatterns:
  - coverage/
  - dist/
  - '**/*.test.js'
  - tmp.js
rules:
  max-params: ['error', 4]
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  unicorn/switch-case-braces: ['error', 'avoid']
  unicorn/no-null: off
  unicorn/no-array-reduce: off
  unicorn/no-nested-ternary: off
  unicorn/prefer-string-replace-all: off
  unicorn/prevent-abbreviations:
    - error
    - allowList:
        fn: true
        err: true
        Ext: true
        ext: true
        def: true
        len: true
        msg: true
        Msg: true
        obj: true
        Obj: true
        Req: true
        req: true
        sep: true
        Sep: true
        str: true
        tmp: true
        args: true
        Attr: true
        attr: true
        prop: true
        Params: true
        params: true
        escAttr: true
        esc-attr: true
